### ISSUE TITLE
Make a binary release

### ISSUE THREAD

**Issue by ye** [antonmedv/red#3]
Tried run `go get github.com/antonmedv/red`, got
```bash
$ go get github.com/antonmedv/red
# github.com/rivo/tview
../../.golang/src/github.com/rivo/tview/util.go:56:2: undefined: runewidth.ZeroWidthJoiner
```

Can we do binary release on GitHub?

**Comment by antonmedv** [comment]
Will do later today.

**Comment by douglascamata** [comment]
FYI, I have the same error when trying to `go get` it from master@117e55d686f4b2f9620b1ec901329bbb57283f4d.

**Comment by jhage-accesso** [comment]
Any movement @antonmedv ?

**Comment by antonmedv** [comment]
Yes :)

**Comment by fearphage** [comment]
> Yes :)

Sweet! Care to elaborate? :smiley:

**Comment by antonmedv** [comment]
Done https://github.com/antonmedv/red/releases :)

**Comment by douglascamata** [comment]
@antonmedv so no more releases since then? The install instructions still don't work.

**Comment by antonmedv** [comment]
Yes. Had no time to work on it.

**Comment by antonmedv** [comment]
Yes, another maintainer will help.
